#!/usr/bin/env bash
#Displaying a process indefinitely
#With a sleep 2 in between each iteration
#I am invincible!!! when receiving a SIGTERM signal

trap 'echo "I am invicible!!!"' SIGTERM
while true
do
	echo "To infinity and beyond"
	sleep 2
done
