#!/usr/bin/env bash
#Writing to terminal the text "Best School" 10 time. "bad luck" is displayed upon the 4th iteration and "good luck" upon the 8th iteration

count=1
while [[ count -lt 11 ]]
do
        if [[ count -eq 4 ]]
        then
                echo "bad luck"
	elif [[ count -eq 8 ]]
	then
		echo "good luck"
        else
        	echo "Best School"
	fi
        count=$(( count+1 ))
done
