#!/usr/bin/env bash
#script that displays:
#The content of the current directory
#In a list format
#Where only the part of the name after the first dash is displayed


lst=$(ls)
for item in $lst; do
	echo "$item" | cut -d "-" -f2
done
